# Generated by Django 5.2.10 on 2026-04-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunSQL(
            sql="CREATE COLLATION IF NOT EXISTS case_insensitive (provider = icu, locale = 'und-u-ks-level2', deterministic = false);",
            reverse_sql="DROP COLLATION IF EXISTS case_insensitive;",
        ),
    ]
