# Generated by Django 5.2.10 on 2026-03-26 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registry", "0001_create_collation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("serial_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("user_id", models.IntegerField(db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "devices",
                "indexes": [
                    models.Index(fields=["user_id"], name="idx_devices_user_id"),
                    models.Index(fields=["is_active"], name="idx_devices_is_active"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "metric_type",
                    models.CharField(
                        db_collation="case_insensitive", max_length=100, unique=True
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("numeric", "Numeric"),
                            ("bool", "Boolean"),
                            ("str", "String"),
                        ],
                        default="numeric",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "metrics",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("data_type__in", ["numeric", "bool", "str"])
                        ),
                        name="check_valid_metric_data_type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceMetric",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registry.device",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="registry.metric",
                    ),
                ),
            ],
            options={
                "db_table": "device_metrics",
                "indexes": [
                    models.Index(fields=["device"], name="idx_device_metrics_device"),
                    models.Index(fields=["metric"], name="idx_device_metrics_metric"),
                ],
                "unique_together": {("device", "metric")},
            },
        ),
    ]
