services:
  web:
    build:
      target: dev-stage
    command: /start-web-dev.sh
    volumes:
      - ./src:/app
      - static_data:/app/staticfiles

  worker:
    build:
      target: dev-stage
    command: [ "celery", "-A", "conf.celery_app", "worker", "-l", "INFO" ]
    volumes:
      - ./src:/app

  celery_beat:
    build:
      target: dev-stage
    volumes:
      - ./src:/app

  kafka-audit-writer:
    volumes:
      - ./src:/app

volumes:
  static_data: